/**
 * ════════════════════════════════════════════════════════════════
 *  MANUALLY MAINTAINED — edit this file freely.
 *  build_timetable.py never touches it.
 * ════════════════════════════════════════════════════════════════
 *
 *  EDGES
 *  ─────
 *  List of [stationA, stationB] undirected connections.
 *  Use station IDs exactly as they appear in network.ts.
 *
 *  EDGE_THICK
 *  ──────────
 *  Set of edges that should be drawn thick (main/express lines).
 *  Key format: sort([stationA, stationB]).join("_")
 *  Example:  EDGE_THICK.add("daejeon_seoul")
 *
 *  EDGE_WAYPOINTS
 *  ──────────────
 *  Intermediate [x, y] bend-points for an edge (same SVG coordinate
 *  space as station positions: x 0–615, y 0–960).
 *  Key format: same sorted-underscore format as EDGE_THICK.
 *  Example:  "daejeon_seoul": [[250, 310], [200, 270]]
 *
 *  STATION_OVERRIDES
 *  ─────────────────
 *  Override the auto-generated x/y for any station.
 *  Keys must be valid StationId values from network.ts.
 *  Example:  seoul: { x: 150, y: 232 }
 * ════════════════════════════════════════════════════════════════
 */

import type { StationId } from "@/shared/types";
import { STATIONS } from "@/data/network";
import type { StationMeta } from "@/data/network";

// ── Edge list ─────────────────────────────────────────────────────────────────

export const EDGES: [StationId, StationId][] = [
  ["haengsin", "seoul"],
  ["seoul", "yongsan"],
  ["yongsan", "yeongdeungpo"],
  ["yeongdeungpo", "gwangmyeong"],
  ["yeongdeungpo", "suwon"],
  ["gwangmyeong", "cheonan_asan"]
];

// ── ADJACENCY (auto-built — do not edit) ─────────────────────────────────────

export const ADJACENCY: Record<StationId, StationId[]> = {};
for (const [a, b] of EDGES) {
  if (!ADJACENCY[a]) ADJACENCY[a] = [];
  if (!ADJACENCY[b]) ADJACENCY[b] = [];
  ADJACENCY[a].push(b);
  ADJACENCY[b].push(a);
}

// ── Thick edges ───────────────────────────────────────────────────────────────
// Add the canonical key (sort([a, b]).join("_")) of any edge that should be
// drawn with a heavier stroke weight.  All other edges are drawn thin.

export const EDGE_THICK = new Set<string>([
  "gwangmyeong_seoul",
]);

// ── Edge waypoints ────────────────────────────────────────────────────────────
// Intermediate [x, y] points that bend a straight edge into a curve.
// Key: sort([stationA, stationB]).join("_")

const EDGE_WAYPOINTS: Record<string, [number, number][]> = {
  "gwangmyeong_yeongdeungpo": [[125.6, 240.0]], // 138.6, 250.0
  // "bugulsan_taehwagang": [[559.5, 624.0], [564.4, 645.4]],
  // "changwon_masan": [[435.9, 710.9]],
  // "cheonan_asan_gwangmyeong": [[164.6, 354.1], [147.7, 331.6], [131.1, 275.0]],
  // "deokso_yangpyeong": [[196.7, 234.7], [205.6, 231.7]],
  // "gangneung_jeongdongjin": [[496.5, 194.6]],
  // "gangneung_jinbu_odaesan": [[485.3, 197.8], [466.9, 196.8]],
  // "gijang_namchang": [[548.7, 696.7]],
  // "gimcheon_gumi_seodaegu": [[369.4, 524.8], [385.9, 532.6], [385.5, 547.9], [395.1, 561.6], [411.2, 567.9], [412.7, 581.3]],
  // "gyeongju_taehwagang": [[518.7, 597.5], [558.9, 623.0], [564.4, 644.7]],
  // "gyeongju_yeongcheon": [[520.1, 594.5], [500.5, 565.8]],
  // "gyeongsan_miryang": [[449.0, 621.2], [463.2, 674.8]],
  // "gyeryong_nonsan": [[191.0, 499.4], [190.1, 512.9]],
  // "iksan_nonsan": [[145.7, 539.4]],
  // "jecheon_wonju": [[343.0, 321.2], [326.8, 308.0], [317.1, 283.9], [299.2, 276.5]],
  // "jeongdongjin_mukho": [[501.6, 214.5]],
  // "jinyeong_miryang": [[472.4, 684.0], [463.7, 681.6]],
  // "mokpo_naju": [[65.1, 796.2], [75.2, 761.5]],
  // "pohang_yeongdeok": [[561.9, 533.6]],
  // "punggi_yeongju": [[429.9, 380.0]],
  // "samcheok_uljin": [[554.2, 294.8]],
  // "uiseong_yeongcheon": [[448.9, 515.3]],
  // "uljin_yeongdeok": [[576.6, 403.9]],
};

// ── Station position overrides ────────────────────────────────────────────────
// Override the auto-generated x/y for any station.
// Keys must be valid StationId values.  Leave empty if you want to use the
// positions generated by build_timetable.py for all stations.

export const STATION_OVERRIDES: Partial<Record<StationId, { x: number; y: number }>> = {
  // Example — uncomment and adjust to reposition a station:
  // seoul: { x: 150, y: 232 },
};

// ── Merged station positions ──────────────────────────────────────────────────
// Use this everywhere instead of STATIONS from network.ts so that overrides
// take effect automatically.

export const STATION_POSITIONS: Record<StationId, StationMeta> = Object.fromEntries(
  Object.entries(STATIONS).map(([id, meta]) => {
    const ov = STATION_OVERRIDES[id as StationId];
    return [id, ov ? { ...meta, ...ov } : meta];
  })
) as Record<StationId, StationMeta>;

// ── Node stations (larger dot + interchange ring) ─────────────────────────────

export const NODE_IDS = new Set<StationId>([
  // "seoul", "busan", "dongdaegu",
]);

// ── Helper functions ──────────────────────────────────────────────────────────

function canonicalKey(a: StationId, b: StationId): string {
  return [a, b].sort().join("_");
}

export function isEdgeThick(a: StationId, b: StationId): boolean {
  return EDGE_THICK.has(canonicalKey(a, b));
}

export function getEdgePoints(a: StationId, b: StationId): [number, number][] {
  const stA = STATION_POSITIONS[a];
  const stB = STATION_POSITIONS[b];
  if (!stA || !stB) return [];
  const key = canonicalKey(a, b);
  const wps = EDGE_WAYPOINTS[key] ?? [];
  const start: [number, number] = [stA.x, stA.y];
  const end: [number, number]   = [stB.x, stB.y];
  const reversed = [a, b].sort()[0] !== a;
  return reversed ? [start, ...[...wps].reverse(), end] : [start, ...wps, end];
}
